"""The 15 Tier-B KPIs: Commerce & Industry, Defence, Education, Skill
Development & Labour, and Road Transport & Highways.

Same contract as ``app/connectors/tier_a/spec.py`` — this module reuses the
``TierAKpi`` / ``TierAkpiTarget`` dataclasses so the pipeline, the frontend and
the provenance API treat Tier-A and Tier-B KPIs identically.

Design rules carried over from Tier-A:

* Every chart is a **single primary series + target lines** (one ``time_line``
  each; Highway Construction renders as bars). Secondary metrics (IIP growth,
  domestic-production value, NAS proficiency, budget vs spend, rail share, …)
  are computed and shown in the data table / provenance panel, never as a
  second axis — this is what keeps text off the plot.
* ``display_title`` is the layman heading on the card; ``name`` (matched to
  ``app/seed_dashboard.py`` and ``app/kpi_specifications.py``) becomes the grey
  technical subtitle.
* ``target`` carries the official / near-term number and the aspirational /
  structural one, from the user's Aug-2026 target table. Where no official
  figure exists the label is "Analytical / desirable level".
"""

from __future__ import annotations

from app.connectors.tier_a.spec import TierAKpi, TierAkpiTarget

_ANALYTICAL = "Analytical / desirable level"


_COMMERCE = [
    TierAKpi(
        ministry_code="COMM",
        key="industrial_import_dependence",
        name="Industrial Imports %",
        display_title="Reliance on Imported Industrial Goods",
        plain_note="Net imports of manufactured / capital goods (excluding oil and gold) as a share of what India consumes. Rising means domestic industry is losing ground to imports. This is an assembled estimate — trade codes do not map cleanly onto production categories.",
        unit="% of demand",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=False,
        valid_range=(0.0, 40.0),
        data_quality="LOW",
        is_proxy=True,
        source_name="DGCI&S trade data + MoSPI National Accounts / IIP (domestic production); import-intensity studies (RBI, NITI Aayog)",
        source_url="https://www.commerce.gov.in/",
        cadence="Annual (manual cross-referencing of trade vs production)",
        datasets=("import_dependence",),
        target=TierAkpiTarget(15.0, 12.0, _ANALYTICAL + " (~15%)", "12-15% within 5-7 years (competitiveness)"),
        secondary_label="Net industrial goods trade balance",
        secondary_unit="$ bn",
    ),
    TierAKpi(
        ministry_code="COMM",
        key="manufacturing_growth",
        name="Manufacturing Growth",
        display_title="Manufacturing's Share of the Economy",
        plain_note="Manufacturing value added as a share of the whole economy (GVA). The 'Make in India' goal is 25%; the share has been stuck near 17% for a decade. Year-on-year factory-output (IIP) growth is in the table.",
        unit="% of GVA",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(10.0, 30.0),
        data_quality="MEDIUM",
        is_proxy=False,
        source_name="MoSPI National Accounts Statistics (manufacturing GVA, current prices) + Index of Industrial Production",
        source_url="https://www.mospi.gov.in/",
        cadence="Annual (GVA share) / Monthly (IIP)",
        datasets=("manufacturing",),
        target=TierAkpiTarget(20.0, 25.0, "~20% of GVA (medium term)", "25% (Make in India)"),
        secondary_label="Manufacturing IIP growth",
        secondary_unit="% YoY",
    ),
    TierAKpi(
        ministry_code="COMM",
        key="pli_effectiveness",
        name="PLI Effectiveness",
        display_title="PLI Scheme Delivery",
        plain_note="How much of the investment that companies committed under the Production-Linked Incentive schemes has actually been made. Realisation figures are largely company self-reports; genuine domestic value-addition (not just assembly) is the real test.",
        unit="% of committed investment",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(0.0, 120.0),
        data_quality="MEDIUM",
        is_proxy=True,
        source_name="DPIIT + sectoral ministry PLI progress reviews; PIB releases",
        source_url="https://dpiit.gov.in/",
        cadence="Annual / Quarterly",
        datasets=("pli",),
        target=TierAkpiTarget(75.0, 100.0, "75% of committed investment realised", "Full realisation + >40-50% domestic value-add"),
        secondary_label="Investment realised",
        secondary_unit="₹'000 Cr",
        period_kind="fiscal_year",
    ),
]

_DEFENCE = [
    TierAKpi(
        ministry_code="DEF",
        key="defence_capex",
        name="Defence CapEx",
        display_title="Defence Modernisation Budget (Share of Economy)",
        plain_note="Money spent on new military equipment and platforms (capital outlay), measured against the size of the economy. Pensions and salaries crowd this out — a flat or falling share means modernisation is being squeezed. Absolute rupee outlay is in the table.",
        unit="% of GDP",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(0.2, 2.0),
        data_quality="HIGH",
        is_proxy=False,
        source_name="Union Budget — Defence Services Estimates (Capital Outlay) + MoSPI Nominal GDP; PRS Legislative Research",
        source_url="https://www.indiabudget.gov.in/",
        cadence="Annual",
        datasets=("capex",),
        target=TierAkpiTarget(0.8, 1.0, "~0.8% of GDP (near-term)", "Toward 1%+ (total defence ~2.5%)"),
        secondary_label="Capital outlay",
        secondary_unit="₹'000 Cr",
    ),
    TierAKpi(
        ministry_code="DEF",
        key="domestic_mic_development",
        name="Domestic MIC Development",
        display_title="Defence Kit Bought from Indian Industry",
        plain_note="Share of the military's equipment-buying budget spent with domestic suppliers rather than foreign ones. Official figures count licensed / assembled production of foreign designs as 'indigenous', so true design self-reliance is lower. Value of domestic defence production is in the table.",
        unit="% of procurement",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(20.0, 100.0),
        data_quality="MEDIUM",
        is_proxy=True,
        source_name="Ministry of Defence / DDP annual reports + PIB; Standing Committee on Defence reports",
        source_url="https://www.mod.gov.in/",
        cadence="Annual",
        datasets=("indigenisation",),
        target=TierAkpiTarget(70.0, 90.0, "~68-70% of capital procurement domestic", "90%+ with real design ownership"),
        secondary_label="Value of domestic defence production",
        secondary_unit="₹'000 Cr",
    ),
    TierAKpi(
        ministry_code="DEF",
        key="force_modernisation",
        name="Force Modernisation",
        display_title="Share of Equipment That Is Modern",
        plain_note="Rough share of major platforms rated 'current' or 'state-of-the-art' rather than vintage — against the armed forces' own doctrine of roughly one-third each. Self-reported and not independently audited; fleet numbers are not disclosed alongside. Capital-budget utilisation is in the table.",
        unit="% of fleet modern",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(30.0, 100.0),
        data_quality="LOW",
        is_proxy=True,
        source_name="Standing Committee on Defence reports + service-headquarters disclosures (vintage / current / state-of-the-art mix)",
        source_url="https://www.mod.gov.in/",
        cadence="Annual",
        datasets=("modernisation",),
        target=TierAkpiTarget(75.0, 85.0, "~two-thirds current or modern", _ANALYTICAL + " (~85%)"),
        secondary_label="Capital acquisition budget used",
        secondary_unit="%",
    ),
]

_EDUCATION = [
    TierAKpi(
        ministry_code="EDU",
        key="learning_outcomes",
        name="Learning Outcomes",
        display_title="Children Reading at Grade Level",
        plain_note="Share of Class 3 children in rural India who can read a Class 2 level text (ASER). This is the single best-tracked measure of foundational learning; it fell after COVID and has only recently recovered toward its 2014 level. The government NAS proficiency figure is in the table.",
        unit="% of Class 3 children",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(0.0, 100.0),
        data_quality="HIGH",
        is_proxy=False,
        source_name="ASER (Pratham) annual rural survey — 'can read Std II text'; National Achievement Survey (NAS) for the table figure",
        source_url="https://asercentre.org/",
        cadence="ASER roughly biennial; NAS periodic",
        datasets=("learning",),
        target=TierAkpiTarget(50.0, 60.0, "50% (NIPUN Bharat / FLN mission direction)", ">60% foundational literacy"),
        secondary_label="NAS Grade 3 language proficiency",
        secondary_unit="%",
    ),
    TierAKpi(
        ministry_code="EDU",
        key="exam_integrity",
        name="Exam Integrity",
        display_title="Major Exam Paper Leaks & Cancellations",
        plain_note="Count of major documented paper leaks or exam cancellations in national and state board / recruitment exams each year. Compiled from press reporting — there is no official register — so treat the level as indicative, not exact. Lower is better.",
        unit="incidents / year",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=False,
        valid_range=(0.0, 40.0),
        data_quality="LOW",
        is_proxy=True,
        source_name="Compiled from national press reporting (paper leaks / cancellations in board, entrance and recruitment exams); Parliament replies where available",
        source_url="https://www.education.gov.in/",
        cadence="Annual (best-effort compilation)",
        datasets=("exam_integrity",),
        target=TierAkpiTarget(2.0, 0.0, _ANALYTICAL + " (near-zero, ≤2/yr)", "Zero major leaks"),
        secondary_label="Aspirants affected (approx.)",
        secondary_unit="lakh",
    ),
    TierAKpi(
        ministry_code="EDU",
        key="enrollment_quality",
        name="Enrollment Quality",
        display_title="Students Staying in School to Class 12",
        plain_note="Gross Enrolment Ratio for senior secondary (Classes 11-12) — how many young people are still in school at that stage, as a share of the age group. Near-universal at the primary level, India still loses many students before Class 12. Pupil-teacher ratio is in the table.",
        unit="% GER (Class 11-12)",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(30.0, 110.0),
        data_quality="MEDIUM",
        is_proxy=False,
        source_name="UDISE+ (Unified District Information System for Education Plus), Ministry of Education",
        source_url="https://udiseplus.gov.in/",
        cadence="Annual",
        datasets=("enrolment",),
        target=TierAkpiTarget(75.0, 100.0, "75% senior-secondary GER (near-term)", "~100% (NEP 2020 goal by 2030)"),
        secondary_label="Pupil-teacher ratio (elementary)",
        secondary_unit=":1",
    ),
]

_SKILL = [
    TierAKpi(
        ministry_code="SKILL",
        key="youth_neet_rate",
        name="Youth NEET Rate",
        display_title="Young People Not in Work, Education or Training",
        plain_note="Share of 15-29 year-olds who are Not in Employment, Education or Training (NEET). A high, sticky rate is the core youth-opportunity problem. Female NEET (in the table) is far higher and is driven heavily by unpaid care work and social norms, not only the job market.",
        unit="% of youth (15-29)",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=False,
        valid_range=(5.0, 45.0),
        data_quality="MEDIUM",
        is_proxy=False,
        source_name="MoSPI Periodic Labour Force Survey (PLFS) Annual Reports; ILO / IHD India Employment Report 2024",
        source_url="https://www.mospi.gov.in/",
        cadence="Annual (with quarterly bulletins)",
        datasets=("neet",),
        target=TierAkpiTarget(18.0, 15.0, "Toward 15-18%", "15% (structural)"),
        secondary_label="Female youth NEET",
        secondary_unit="%",
    ),
    TierAKpi(
        ministry_code="SKILL",
        key="apprenticeship_utilisation",
        name="Apprenticeship Utilisation",
        display_title="Apprenticeship Budget Actually Spent",
        plain_note="Share of the money budgeted for apprenticeship schemes (NAPS / NATS) that is actually spent in the year. Historically a large chunk went unspent. High spending still needs to convert into real placements to count as success. Rupee allocation vs spend is in the table.",
        unit="% of budget used",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(0.0, 110.0),
        data_quality="MEDIUM",
        is_proxy=False,
        source_name="Union Budget / Outcome Budget (MSDE) — apprenticeship scheme allocation vs actual expenditure; Standing Committee on Labour reports",
        source_url="https://www.msde.gov.in/",
        cadence="Annual",
        datasets=("apprenticeship",),
        target=TierAkpiTarget(80.0, 95.0, ">70-80% budget utilisation", "95%+ with strong placement outcomes"),
        secondary_label="Budget allocated",
        secondary_unit="₹ Cr",
    ),
    TierAKpi(
        ministry_code="SKILL",
        key="job_creation",
        name="Job Creation",
        display_title="New Formal Jobs Added (EPFO)",
        plain_note="Net new subscribers to the EPFO retirement fund each year — the standard proxy for formal job creation. It also captures existing jobs being formalised and workers re-registering, so it overstates genuinely new jobs. Youth (18-28) share is in the table.",
        unit="lakh / year",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=True,
        valid_range=(0.0, 250.0),
        data_quality="MEDIUM",
        is_proxy=True,
        source_name="EPFO payroll estimates (net subscriber additions), released monthly; MoSPI",
        source_url="https://www.epfindia.gov.in/",
        cadence="Monthly / Annual",
        datasets=("jobs",),
        target=TierAkpiTarget(130.0, 160.0, _ANALYTICAL + " (~130 lakh/yr)", "Rising formal-job share for the 15-29 cohort"),
        secondary_label="Age 18-28 share of additions",
        secondary_unit="%",
    ),
]

_ROAD = [
    TierAKpi(
        ministry_code="ROAD",
        key="logistics_cost_pct",
        name="Logistics Cost %",
        display_title="Cost of Moving Goods (Share of Economy)",
        plain_note="Total national logistics cost (transport + warehousing + handling) as a share of GDP. Lower means a more competitive economy. The often-quoted '13-14%' legacy figure had no rigorous basis; the NCAER-DPIIT study puts it near 8%. The pre-2022 points here are rough estimates — see the caveat.",
        unit="% of GDP",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=False,
        valid_range=(4.0, 18.0),
        data_quality="MEDIUM",
        is_proxy=True,
        source_name="NCAER–DPIIT 'Assessment of Logistics Cost in India' (FY2021-22 onwards); earlier points are legacy estimates (Economic Survey / industry bodies)",
        source_url="https://dpiit.gov.in/",
        cadence="Periodic",
        datasets=("logistics_cost",),
        target=TierAkpiTarget(8.0, 6.0, "~8% of GDP (National Logistics Policy)", "6-8% (advanced-economy range)"),
    ),
    TierAKpi(
        ministry_code="ROAD",
        key="highway_construction",
        name="Highway Construction",
        display_title="National Highway Built per Day",
        plain_note="Average kilometres of national highway constructed per day over the year. A headline delivery metric — note that some years mix new construction with widening / upgrade of existing roads. Total km built is in the table.",
        unit="km / day",
        data_shape="time_line",
        chart_type="bar",
        higher_is_better=True,
        valid_range=(0.0, 60.0),
        data_quality="HIGH",
        is_proxy=False,
        source_name="Ministry of Road Transport & Highways / NHAI — annual physical progress; PIB",
        source_url="https://morth.nic.in/",
        cadence="Monthly (running km/day) / Annual",
        datasets=("highway_pace",),
        target=TierAkpiTarget(33.0, 45.0, "Sustain 30+ km/day", "40+ km/day of high-quality NH"),
        secondary_label="Total NH constructed",
        secondary_unit="km",
    ),
    TierAKpi(
        ministry_code="ROAD",
        key="modal_share",
        name="Modal Share",
        display_title="Freight Still Moving by Road",
        plain_note="Road's share of the country's goods movement (tonne-km). India is heavily road-dependent; national policy wants to shift freight to rail and waterways, which are cheaper and cleaner. Rail and other-mode shares are in the table.",
        unit="% of freight tonne-km",
        data_shape="time_line",
        chart_type="line",
        higher_is_better=False,
        valid_range=(40.0, 80.0),
        data_quality="MEDIUM",
        is_proxy=True,
        source_name="NITI Aayog freight-mode studies + MoRTH + Indian Railways (rail comparison); not one reconciled national freight survey",
        source_url="https://morth.nic.in/",
        cadence="Annual",
        datasets=("modal_share",),
        target=TierAkpiTarget(62.0, 55.0, "Arrest the rise (~62%)", "~55% as rail rises toward 40%+"),
        secondary_label="Rail share of freight",
        secondary_unit="%",
    ),
]

TIER_B_KPIS: list[TierAKpi] = _COMMERCE + _DEFENCE + _EDUCATION + _SKILL + _ROAD
assert len(TIER_B_KPIS) == 15, f"expected 15 Tier-B KPIs, got {len(TIER_B_KPIS)}"

TIER_B_BY_KEY: dict[str, TierAKpi] = {k.key: k for k in TIER_B_KPIS}
TIER_B_BY_NAME: dict[tuple[str, str], TierAKpi] = {(k.ministry_code, k.name): k for k in TIER_B_KPIS}
TIER_B_MINISTRIES: tuple[str, ...] = ("COMM", "DEF", "EDU", "SKILL", "ROAD")
